### ISSUE TITLE
make macos - failing.

### ISSUE THREAD

**Issue by johndpope** [s1ddok/Fiber2D#10]
cd external/SwiftBGFX
sh prepare_bgfx_macos.sh
Building configurations...
Running action 'ninja'...
Generating ../.build/projects/ninja-osx/Makefile...
Generating ../.build/projects/ninja-osx/debug32/build.ninja...
Generating ../.build/projects/ninja-osx/release32/build.ninja...
Generating ../.build/projects/ninja-osx/debug64/build.ninja...
Generating ../.build/projects/ninja-osx/release64/build.ninja...
Generating ../.build/projects/ninja-osx/debug/build.ninja...
Generating ../.build/projects/ninja-osx/release/build.ninja...
Generating ../.build/projects/ninja-osx/debug32/bgfx.ninja...
Generating ../.build/projects/ninja-osx/release32/bgfx.ninja...
Generating ../.build/projects/ninja-osx/debug64/bgfx.ninja...
Generating ../.build/projects/ninja-osx/release64/bgfx.ninja...
Generating ../.build/projects/ninja-osx/debug/bgfx.ninja...
Generating ../.build/projects/ninja-osx/release/bgfx.ninja...
Generating ../.build/projects/ninja-osx/debug32/bx.ninja...
Generating ../.build/projects/ninja-osx/release32/bx.ninja...
Generating ../.build/projects/ninja-osx/debug64/bx.ninja...
Generating ../.build/projects/ninja-osx/release64/bx.ninja...
Generating ../.build/projects/ninja-osx/debug/bx.ninja...
Generating ../.build/projects/ninja-osx/release/bx.ninja...
Generating ../.build/projects/ninja-osx/debug32/bimg.ninja...
Generating ../.build/projects/ninja-osx/release32/bimg.ninja...
Generating ../.build/projects/ninja-osx/debug64/bimg.ninja...
Generating ../.build/projects/ninja-osx/release64/bimg.ninja...
Generating ../.build/projects/ninja-osx/debug/bimg.ninja...
Generating ../.build/projects/ninja-osx/release/bimg.ninja...
Generating ../.build/projects/ninja-osx/debug32/bimg_decode.ninja...
Generating ../.build/projects/ninja-osx/release32/bimg_decode.ninja...
Generating ../.build/projects/ninja-osx/debug64/bimg_decode.ninja...
Generating ../.build/projects/ninja-osx/release64/bimg_decode.ninja...
Generating ../.build/projects/ninja-osx/debug/bimg_decode.ninja...
Generating ../.build/projects/ninja-osx/release/bimg_decode.ninja...
Done. Generated 31/31 projects.
make: ninja: No such file or directory
make: *** [clean] Error 1
make: ninja: No such file or directory
make: *** [clean] Error 1
==== Building bgfx (debug64) ====
make: ninja: No such file or directory
make: *** [bgfx] Error 1
==== Building bgfx (release64) ====
make: ninja: No such file or directory
make: *** [bgfx] Error 1

make macos
swift build -Xswiftc -Iexternal/SwiftBGFX/3rdparty/bgfx/3rdparty/khronos -Xswiftc -Iexternal/SwiftBGFX/3rdparty/bx/include -Xswiftc -Iexternal/SwiftBGFX/3rdparty/bgfx/3rdparty -Xlinker -lc++ -Xlinker -lbgfxDebug -Xlinker -lbxDebug -Xlinker -lbimgDebug -Xlinker -lz -Xcc -DCP_USE_CGTYPES=0 -Xlinker -framework -Xlinker AppKit -Xlinker -framework -Xlinker Quartz -Xlinker -Lexternal/SwiftBGFX/3rdparty/bgfx/.build/osx64_clang/bin -Xcc -Iexternal/SwiftBGFX/3rdparty/bx/include/compat/osx -Xcc -DBGFX_CONFIG_RENDERER_METAL=1 -Xlinker -framework -Xlinker Metal -Xlinker -framework -Xlinker MetalKit -Xlinker -framework -Xlinker Foundation
Compile Swift Module 'Fiber2D' (106 sources)
/Users/jpope/Desktop/Fiber2D/Fiber2D/Node+Scene.swift:32:22: error: missing argument for parameter #1 in call
        onEnter.fire()
                     ^
                     <#Void#>
/Users/jpope/Desktop/Fiber2D/Fiber2D/events/Event.swift:79:17: note: 'fire' declared here
    public func fire(_ data: T) {
                ^
/Users/jpope/Desktop/Fiber2D/Fiber2D/Node+Scene.swift:37:41: error: missing argument for parameter #1 in call
        onEnterTransitionDidFinish.fire()
                                        ^
                                        <#Void#>
/Users/jpope/Desktop/Fiber2D/Fiber2D/events/Event.swift:79:17: note: 'fire' declared here
    public func fire(_ data: T) {
                ^
/Users/jpope/Desktop/Fiber2D/Fiber2D/Node+Scene.swift:42:39: error: missing argument for parameter #1 in call
        onExitTransitionDidStart.fire()
                                      ^
                                      <#Void#>
/Users/jpope/Desktop/Fiber2D/Fiber2D/events/Event.swift:79:17: note: 'fire' declared here
    public func fire(_ data: T) {
                ^
/Users/jpope/Desktop/Fiber2D/Fiber2D/Node+Scene.swift:56:21: error: missing argument for parameter #1 in call
        onExit.fire()
                    ^
                    <#Void#>
/Users/jpope/Desktop/Fiber2D/Fiber2D/events/Event.swift:79:17: note: 'fire' declared here
    public func fire(_ data: T) {
                ^
/Users/jpope/Desktop/Fiber2D/Fiber2D/ActionEase.swift:32:16: error: simultaneous accesses to parameter 'self', but modification requires exclusive access; consider copying to a local variable
        action.update(state: easeBlock(state))
        ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jpope/Desktop/Fiber2D/Fiber2D/ActionEase.swift:32:30: note: conflicting access is here
        action.update(state: easeBlock(state))
                             ^~~~~~~~~
/Users/jpope/Desktop/Fiber2D/Fiber2D/ActionRepeat.swift:87:32: error: simultaneous accesses to parameter 'self', but modification requires exclusive access; consider copying to a local variable
                innerContainer.update(state: dt - (nextDt - 1.0 / Float(repeatCount)))
                ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jpope/Desktop/Fiber2D/Fiber2D/ActionRepeat.swift:87:52: note: conflicting access is here
                innerContainer.update(state: dt - (nextDt - 1.0 / Float(repeatCount)))
                                                   ^~~~~~
/Users/jpope/Desktop/Fiber2D/Fiber2D/ActionRepeat.swift:87:32: error: simultaneous accesses to parameter 'self', but modification requires exclusive access; consider copying to a local variable
                innerContainer.update(state: dt - (nextDt - 1.0 / Float(repeatCount)))
                ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jpope/Desktop/Fiber2D/Fiber2D/ActionRepeat.swift:87:73: note: conflicting access is here
                innerContainer.update(state: dt - (nextDt - 1.0 / Float(repeatCount)))
                                                                        ^~~~~~~~~~~
/Users/jpope/Desktop/Fiber2D/Fiber2D/ActionRepeat.swift:71:32: error: simultaneous accesses to parameter 'self', but modification requires exclusive access; consider copying to a local variable
                innerContainer.start(with: target)
                ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/Users/jpope/Desktop/Fiber2D/Fiber2D/ActionRepeat.swift:71:44: note: conflicting access is here
                innerContainer.start(with: target)
                                           ^~~~~~
/Users/jpope/Desktop/Fiber2D/Fiber2D/ActionRepeat.swift:109:28: error: simultaneous accesses to parameter 'self', but modification requires exclusive access; consider copying to a local variable
            innerContainer.start(with: target)
            ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/Users/jpope/Desktop/Fiber2D/Fiber2D/ActionRepeat.swift:109:40: note: conflicting access is here
            innerContainer.start(with: target)
                                       ^~~~~~
/Users/jpope/Desktop/Fiber2D/Fiber2D/ActionRepeat.swift:40:28: error: simultaneous accesses to parameter 'self', but modification requires exclusive access; consider copying to a local variable
            innerContainer.start(with: target)
            ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
/Users/jpope/Desktop/Fiber2D/Fiber2D/ActionRepeat.swift:40:40: note: conflicting access is here
            innerContainer.start(with: target)
                                       ^~~~~~
/Users/jpope/Desktop/Fiber2D/Fiber2D/ActionSequence.swift:37:28: error: simultaneous accesses to parameter 'self', but modification requires exclusive access; consider copying to a local variable
                actions[0].start(with: target)
                       ~~~~^~~~~~~~~~~~~~~~~~~
/Users/jpope/Desktop/Fiber2D/Fiber2D/ActionSequence.swift:37:40: note: conflicting access is here
                actions[0].start(with: target)
                                       ^~~~~~
/Users/jpope/Desktop/Fiber2D/Fiber2D/ActionSequence.swift:61:28: error: simultaneous accesses to parameter 'self', but modification requires exclusive access; consider copying to a local variable
            actions[found].start(with: target)
                   ~~~~~~~~^~~~~~~~~~~~~~~~~~~
/Users/jpope/Desktop/Fiber2D/Fiber2D/ActionSequence.swift:61:40: note: conflicting access is here
            actions[found].start(with: target)
                                       ^~~~~~
/Users/jpope/Desktop/Fiber2D/Fiber2D/System.swift:47:12: warning: redundant conformance constraint 'T': 'Component'
    where T: Component {
           ^
/Users/jpope/Desktop/Fiber2D/Fiber2D/System.swift:46:48: note: conformance constraint 'T': 'Component' inferred from type here
    public func subtree<T>(of type: T.Type) -> ComponentNode<T>
                                               ^
/Users/jpope/Desktop/Fiber2D/Fiber2D/System.swift:47:12: warning: redundant conformance constraint 'T': 'Component'
    where T: Component {
           ^
/Users/jpope/Desktop/Fiber2D/Fiber2D/System.swift:46:48: note: conformance constraint 'T': 'Component' inferred from type here
    public func subtree<T>(of type: T.Type) -> ComponentNode<T>
                                               ^
error: terminated(1): /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/jpope/Desktop/Fiber2D/.build/debug.yaml
make: *** [macos] Error 1


Welcome to Apple Swift version 4.0 (swiftlang-900.0.43 clang-900.0.22.8). Type :help for assistance.


<img width="1381" alt="screen shot 2017-06-26 at 10 44 42 am" src="https://user-images.githubusercontent.com/289994/27544915-8bb7d3da-5a5c-11e7-9915-f307bf1f6bd2.png">

**Comment by s1ddok** [comment]
Things are fairly broken now and readme is outdated, I will try to fix it asap

**Comment by s1ddok** [comment]
`ninja build` of bgfx doesn't work anymore, one should use `make` inside `bgfx` folder to make it work.
