### ISSUE TITLE
Swift and Kotlin

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [s1ddok/Fiber2D#11]
I just want to talk about Swift and it's future.

First rumors was like Google want to make it first class lang: https://thenextweb.com/dd/2016/04/07/google-facebook-uber-swift/

Currently for cross-platform game development I'm using cocos2d-x and C++, which is supported by platform IDE's: Xcode and android studio. This gives me a top level of controll and I can easy use any new features in these IDE's. Overall like I can say - ability to work natively. This is really cool. But what is not cool, it's C++. It's fast, powerful but it's not easy to learn it and overall it's too complicated.. 

So, I waited for Swift to be official on android maybe.. But what do we have now: **Kotlin is now an official android language.**
https://developer.android.com/kotlin/index.html
https://android-developers.googleblog.com/2017/05/android-announces-support-for-kotlin.html

Swift is like Kotlin. Or better to say vice versa? Kotlin first appeared at 2011, but Swift at 2014. Well, whatever..
And fun to compare some syntax of both languages:
http://nilhcem.com/swift-is-like-kotlin/

Anyway, this means **no way for Swift for android**. I don't believe that Google has any plans for it.

Finally, looks like C++ is only the one right way.. and we have cocos2d-x, but they currently moving into wrong direction - to JS. Also, they developing closed-source editor, same crappy as was android studio. For me it's like "china low quality product".  

Any ideas, thought about all this?

p.s. pls don't close this issue to early. cocos2d forum died, so no place to talk about this I think.

**Comment by fluidityt** [comment]
probably best to do something with libgdx, kotlin, and a roboVM fork :( until this project is awesomesauce.

**Comment by s1ddok** [comment]
The problem with Kotlin is that it is still Java inside. So all problems are inherited with it. 

This project is more like proof of a concept, but potentially can beat all medio-core frameworks with performance and API design. 

However in the world of Unity and UE4 it is mostly for indie devs and for learning programming purposes.

**Comment by Anywhere-Music-Player** [comment]
@fluidityt I will stay with C++ anyway, because I'm using Xcode and macOS for development only. 

What I'm seeing about cocos2d-x now - they are moving into JS and will likely lose many C++ devs. Also their new crappy editor.. ohh omg.. 
But all these is a chance, for something new.. 

Qt is a good way to develop a cross-platform editor using C++ and so if engine can be C++ it's much easier overall to contribute. 

So, what I'm saying: all tools are ready for now, just need a proper realization..

**Comment by oxeron** [comment]
> pls don't close this issue to early. cocos2d forum died, so no place to talk about this I think.

This one is not dead : http://forum.cocos2d-objc.org

**Comment by Anywhere-Music-Player** [comment]
Ohh, wrong button, closed by mistake.
By dead I mean there is nothing.. but dust.

**Comment by Anywhere-Music-Player** [comment]
So, @s1ddok any ideas about to make a new engine with same ideas.. but C++?

**Comment by s1ddok** [comment]
No, luckily for me my interference with C++ is down to minimum and I'm super happy about it. It may have some performance beast type of things, but I'd rather stick with Swift.

**Comment by Anywhere-Music-Player** [comment]
https://www.theverge.com/google/2017/11/20/16681556/apple-swift-language-google-fuchsia-os-open-source
