### ISSUE TITLE
[Question] Interaction with native iOS / Android

### ISSUE THREAD

**Issue by marckaraujo** [s1ddok/Fiber2D#6]
This lib can or will be possible to call methods from native view?

More info about this question: http://stackoverflow.com/questions/41638598/interact-with-cocos2d-x-scene-at-android-ios-native-window

Thanks,

**Comment by s1ddok** [comment]
Yes, the goal is to make Fiber2D fully modular and embedabble. As you can see iOS/macOS demo is done by creating special UIView that contains Fiber2D director and scene stack. You can of course to add native buttons and call Scene's methods. It will be much harder on Android, but still possible.

**Comment by marckaraujo** [comment]
Nice, so we should start using your framework as soon as it become more stable. When do you plan to release a beta?

**Comment by s1ddok** [comment]
I guess 1-2 months. I'm done porting stuff (`Windows` port is delayed) and now I want to get back working on API itself.
