### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [s1ddok/Fiber2D#9]
Abandoned?

**Comment by s1ddok** [comment]
Not really. Been busy lately, but is going to continue commiting before WWDC with some neat features

**Comment by Anywhere-Music-Player** [comment]
Lol that fast). Hope the best.

**Comment by Anywhere-Music-Player** [comment]
Hmm, https://android-developers.googleblog.com/2017/05/android-announces-support-for-kotlin.html 

Bye SWIFT, hello Kotlin. 

I will use only language for cross-platform development which is supported by platform IDE, like Xcode and android studio. That means no way for SWIFT as language for cross-platform game development. Looks like C++ is only one right way..

**Comment by Anywhere-Music-Player** [comment]
Any ideas?
